- Makefile
- scripts/alpine-setup.sh
This fixes build to produce static binaries - the `CGO_ENABLE` did not get propagated in the GH action build container.
Fixes #1
> Fix static build

- pkg/collector/cluster.go
- rules/deprecated-1-16.rego
- rules/deprecated-1-20.rego
This PR moves logic to unpack manifest from `kubectl.kubernetes.io/last-applied-configuration`, in case of Cluster collector, from OPA rules to collector itself. This unifies handling for all collectors.
This also fixes bug when resources from Cluster collector might be flagged as deprecated, even if they were created with a non-deprecated API version.
> (ref) Move logic to unpack last-applied config to collector

- .github/workflows/main.yaml
- .gitignore
- Makefile
- pkg/collector/cluster_test.go
Will add Github Actions testing, this is just making sure you are ok with the flow.
> Added first test

- Makefile
- rules/deprecated-1-16.rego
- rules/deprecated-1-20.rego
- scripts/alpine-setup.sh
This PR introduces changes required to support local file collector - **Rego rules - support resources without namespace** - and also adds `opa fmt` and `go fmt` checks.
> Support resources without Namespace + fmt checks

- pkg/collector/file.go
- pkg/collector/file_test.go
- pkg/config/config.go
This PR adds support for stdin input for File collector. Usage: `-f -`.
```
$ cat manifest.yaml | ./kubent -f-
```
Fixes #6
> Add stdin support for File collector

- cmd/kubent/main.go
- pkg/collector/cluster.go
- pkg/collector/collector.go
- pkg/collector/file.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/judge/judge.go
- pkg/judge/rego.go
This should cover #13 and add better visibility when we fail to parse resources.
The `kubent` will now report details about resource that failed to be parsed:
```
6:07PM ERR Failed to retrieve data from collector error="failed to parse last-applied-configuration annotation of resource default/test-ingress: invalid character '{' looking for beginning of object key s
tring" name=Cluster
```
> Better error reporting

- pkg/judge/rego.go
- pkg/judge/rego_test.go
This PR makes an empty output (i.e. no issues found) in json format to be an empty array  (instead of null). This is more friendly for CI use (#31), such as with jq.
Before:
```
$./bin/kubent-darwin-amd64 -o json                                                                                                                       2
2:36PM INF >>> Kube No Trouble `kubent` <<<
...
...
null
```
After:
```
$./bin/kubent-darwin-amd64 -o json                                                                                                                     130
3:09PM INF >>> Kube No Trouble `kubent` <<<
...
...
[]
```
> Empty json output to array

- README.md
- pkg/printer/json.go
This PR adds docs section on how to use the tool in CI, in regards to exit code, with some example.
> Docs: Add CI use section

- README.md
- cmd/kubent/main.go
- cmd/kubent/main_test.go
- pkg/config/config.go
This PR adds `--exit-error` (`-e`) flag for convenience. When enabled this will make `kubent` return non-zero exit code in case any issues are found. Also, tests for exit codes are added. 
Fixes #31.
> Add --exit-error (-e) flag

- .github/dependabot.yml
This should enable Dependabot and creation of automatic PRs for Go module updates & docker.
Fixes #28
> build: Enable Dependabot

- .github/workflows/main.yaml
- .gitignore
- .pre-commit-config.yaml
- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
> Pre-commit

- .github/workflows/main.yaml
- Makefile
- README.md
- scripts/git-check-commits.sh
This PR adds check and docs for commit message format.
> build: Add check for commit message format

- .github/workflows/main.yaml
- Makefile
- README.md
- scripts/alpine-setup.sh
- scripts/changelog.tmpl
- scripts/github-changelog.sh
This PR adds tooling and plumbing for changelog generation, based on PRs and their labels.
Initially to be used to prepare changelog for releases (still manual step) and for nightly releases (fully automated). Details are described in README.
> Add changelog generation plumbing

- .github/workflows/main.yaml
- .github/workflows/nightly.yaml
This should create a nightly build if there are any changes... currently figuring out a way to test.
> ci: Create Nightly releases

- .github/workflows/nightly.yaml
Only releases (x.y.z) should be considered for deriving nightly build names.
This should prevent issue like `nightly-nightly-0.3.2-xx-test-4-g8092735`, which was derived from `nightly-0.3.2-xx-test`.
> ci: Only consider x.y.z releases for builiding nightly tags

- rules/deprecated-1-16.rego
Hi again 👋 ! 
I've found that the msg of the 1.16 deprecation ruleset has an extra whitespace at the end, I think it's a little bit annoying for consuming the json output with `jq`  so I removed it in this PR. 
Let me know if that's ok.
Thanks!
> Removing whitespace at the end of the ruleset 1.16 msg

- .github/workflows/nightly.yaml
This should fix unintended nightly runs if the nightly tag does exists, such as:
https://github.com/doitintl/kube-no-trouble/runs/1561223081?check_suite_focus=true
> ci: Prevent runs if nightly tag exists

- fixtures/fake-tokenReview-deprecated.yaml
- rules/deprecated-1-22.rego
This PR add depreciation rules for following API:
- Coordination.k8s.io/v1beta1  _(target removal in 1.22)_
- authentication.k8s.io/v1beta1 _(removed in 1.22)_
- authorization.k8s.io/v1beta1 _(removed in 1.22)_
source :
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#deprecation
> feat: Add deprecation rules (coordination, authentication, authorization) in 1.22 ruleset

- pkg/collector/helm2.go
- pkg/collector/helm3.go
> fix: Default the Helm manifest namespace to the release namespace

- .github/workflows/main.yaml
- Makefile
> feat: Windows release

- .github/workflows/main.yaml
This should fix failing _Upload Release Asset_ steps (https://github.com/doitintl/kube-no-trouble/runs/2251044417?check_suite_focus=true):
```yaml
Run actions/upload-release-asset@v1
with:
asset_path: ./release-artifacts/kubent-nightly-0.3.2-98-ga011986-linux-amd64.tar.gz
asset_name: kubent-nightly-0.3.2-98-ga011986-linux-amd64.tar.gz
asset_content_type: application/tar+gzip
env:
GITHUB_TOKEN: ***
Error: Input required and not supplied: upload_url
```
using the [jobs outputs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs).
> ci: Fix failing Upload Release Asset steps

- .gitignore
- Makefile
- README.md
- cmd/kubent/main.go
- fixtures/issuer-v1alpha2.yaml
- pkg/collector/cluster.go
- pkg/collector/cluster_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/judge/rego_test.go
- pkg/rules/rego/custom.rego.tmpl
- pkg/rules/rules.go
- pkg/rules/rules_test.go
- test/rules_test.go
~*WIP: Still needs:*~
---
This PR adds support for detecting and flagging custom resources.
```
kubent -a "ManagedCertificate.v1.networking.gke.io"
```
The `-a` flag, or it's full form `--additional-kind`, can be used multiple times.
The expected format is full `Kind.version.group.com` form - e.g. `ManagedCertificate.v1.networking.gke.io`.
Closes #44
> feat: Add support for custom resources

- README.md
- cmd/kubent/main.go
- cmd/kubent/main_test.go
- pkg/collector/cluster.go
- pkg/collector/cluster_test.go
- pkg/collector/collector.go
- pkg/collector/fake.go
- pkg/collector/file.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
- pkg/config/config.go
- pkg/config/config_test.go
This PR adds support for detecting version of K8s server. It's a foundation for being able to filter relevant findings later on.
From #130:
WIP, apart from above it's missing:
This PR addresses first half of #130.
> Feat: Detect K8s version

- .github/workflows/main.yaml
This should fix issue where the build is referencing non-existing artifact  - https://github.com/doitintl/kube-no-trouble/runs/2626121412?check_suite_focus=true
> ci: Correct reference to non-existing build artifact

- pkg/collector/cluster_test.go
We can use fake client in this test, avoiding waiting for timeouts.
original:
```
=== RUN   TestNewClusterCollectorValidEmptyCollector
--- PASS: TestNewClusterCollectorValidEmptyCollector (330.04s)
```
new:
```
=== RUN   TestNewClusterCollectorValidEmptyCollector
--- PASS: TestNewClusterCollectorValidEmptyCollector (0.00s)
```
Closes #155
> test: Fix slow TestNewClusterCollectorValidEmptyCollector

- fixtures/priorityclass-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
Cover deprecated `scheduling.k8s.io/v1beta1` - PriorityClass resource
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide/ add PriorityClass resource.
Review after #156, it will be easier :)
Part of #135
> feat: Cover deprecated `scheduling.k8s.io/v1beta1` - PriorityClass resource

- fixtures/clusterrole-v1beta1.yaml
- fixtures/clusterrolebinding-v1beta1.yaml
- fixtures/role-v1beta1.yaml
- fixtures/rolebinding-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
Cover deprecated `rbac.authorization.k8s.io/v1beta1` - RBAC resources
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide/ add `rbac.authorization.k8s.io/v1beta1` group of resources.
Review after #156, it will be easier :)
Part of #135
> feat: Cover deprecated `rbac.authorization.k8s.io/v1beta1` - RBAC resources

- fixtures/ingressclass-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
Cover deprecated `networking.k8s.io/v1beta1` - Ingress* resources
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide/, add `networking.k8s.io/v1beta1` group of resources.
Part of #135
Fixes #94
> feat: Cover deprecated `networking.k8s.io/v1beta1` - Ingress* resources

- fixtures/lease-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
This PR is about minor fixes and adding test for `coordination.k8s.io/v1beta1` API group.
Changes:
- fix: Add Leases to be pulled by cluster collector
- fix: Remove LeaseList from rules
- test: Add test for Lease
#135, #113
> fix: Remove `LeaseList` and add `Lease` to cluster collector, add test for `Lease`

- fixtures/certificatesigningrequest-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
This PR adds coverage of deprecated certificates.k8s.io/v1beta1 API group
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide/,
add `certificates.k8s.io/v1beta1` group of resources.
Part of #135
> feat: Cover deprecated `certificates.k8s.io/v1beta1` API group

- fixtures/localsubjectaccessreview-v1beta1.yaml
- fixtures/selfsubjectaccessreview-v1beta1.yaml
- fixtures/subjectaccessreview-v1beta1.yaml
- fixtures/tokenreview-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
This PR adds coverage of deprecated  `authorization.k8s.io/v1beta1` and `authentication.k8s.io/v1beta1` API groups
- SelfSubjectAccessReview, LocalSubjectAccessReview, SubjectAccessReview
- TokenReview resources.
Part of #135
> feat: Cover deprecated `auth*.k8s.io/v1beta1` API groups

- pkg/collector/cluster.go
- Fixes typo in cluster collector - PriorityClass api version:
- Fixes certificates.k8s.io API version
> fix: Minor fixes of API versions in cluster collector

- fixtures/apiservice-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
This PR adds coverage of deprecated `apiregistration.k8s.io/v1beta1` API group - `APIService` resource.
Part of #135
> feat: Cover deprecated `apiregistration.k8s.io/v1beta1` API group

- fixtures/customresourcedefinition-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
This PR adds coverage for deprecated `apiextensions.k8s.io/v1beta1` API group - `CustomResourceDefinition` resource.
Part of #135
> feat: Cover deprecated `apiextensions.k8s.io/v1beta1` API group

- fixtures/mutatingwebhookconfiguration-v1beta1.yaml
- fixtures/validatingwebhookconfiguration-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- test/rules_122_test.go
This PR adds coverage for the deprecated `admissionregistration.k8s.io/v1beta1` API group
add admissionregistration.k8s.io/v1beta1 group of resources:
- `MutatingWebhookConfiguration`
- `ValidatingWebhookConfiguration`
Part of #135
> feat: Cover deprecated `admissionregistration.k8s.io/v1beta1` API group

- .gitignore
- fixtures/runtimeclass-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-22.rego
- pkg/rules/rego/deprecated-1-25.rego
- test/helper.go
- test/rules_122_test.go
- test/rules_125_test.go
This PR adds coverage of deprecated `node.k8s.io/v1beta1` API group - `RuntimeClass` resource.
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide.
Part of #135
> feat: Cover deprecated `node.k8s.io/v1beta1` API group

- fixtures/poddisruptionbudget-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-25.rego
- test/rules_125_test.go
Cover deprecated policy/v1beta1 API group - PDB
add `policy/v1beta1` group - `PodDisruptionBudget` resource.
Part of #135
Easier to review after #171
> feat: Cover deprecated `policy/v1beta1` API group - PodDisruptionBudget

- fixtures/podsecuritypolicy-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-25.rego
- test/rules_125_test.go
This PR adds coverage of removed `policy/v1beta1` API group - `PodSecurityPolicy` resource.
add `policy/v1beta1z group - zPodSecurityPolicy` resource.
Part of #135
Easier to review after #172
> feat: Cover removed `policy/v1beta1` API group - PodSecurityPolicy

- fixtures/endpointslice-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-25.rego
- test/rules_125_test.go
This PR adds coverage of deprecated `discovery.k8s.io/v1beta1` API group - `EndpointSlice` resource.
add `discovery.k8s.io/v1beta1` group - `EndpointSlice` resource.
Part of #135
Easier to review after #171
> feat: Cover deprecated `discovery.k8s.io/v1beta1` API group - EndpointSlice

- fixtures/cronjob-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-25.rego
- test/rules_125_test.go
This PR adds coverage for deprecated `batch/v1beta1` API group - `CronJob` resource
add `batch/v1beta1` group - `CronJob` resource.
Part of #135
Easier to review once #172 is merged.
> feat: Cover deprecated `batch/v1beta1` API group - CronJob

- cmd/kubent/main.go
- cmd/kubent/main_test.go
- go.mod
- go.sum
- pkg/collector/collector.go
- pkg/collector/fake.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/version.go
- pkg/judge/judge.go
- pkg/judge/rego.go
- pkg/printer/filter.go
- pkg/printer/filter_test.go
- pkg/printer/json_test.go
This PR implements filtering of non-relevant versions, i.e. versions that the user can't upgrade to as they're not available in the used K8S version.
Closes #130
> feat: Filter non-relevant results

- pkg/collector/cluster.go
When resources are not available in the cluster, and this is expected to
happen, don't spam users with WARN log messages.
Closes #185
> ref: Adjust log level to debug for expected situation when resources are not available

- fixtures/kube.config.basic
- pkg/collector/cluster.go
- pkg/collector/cluster_test.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
- pkg/config/config.go
- pkg/config/config_test.go
This PR addresses multiple kubeconfig files support via `KUBECONFIG` env variable, as per #123.
It removes parsing of `KUBECONFIG` env variable and relies on functionality in `client-go` packaged. This in turn, apart from multiple files support, should also make behaviour more consistent with `kubectl` and other tools.
_I'm planning to add support for context in separate PR._
> feat: Support multiple kubeconfig files

- README.md
- cmd/kubent/main.go
- fixtures/kube.config.context
- pkg/collector/cluster.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
- pkg/config/config.go
- pkg/config/config_test.go
This PR adds support to configure Kubernetes context via `--context (-x)` flag.
Addresses second part of #123
> feat: Add --context (-x) option to select Kube context

- pkg/collector/cluster.go
- pkg/collector/fake.go
- pkg/collector/file.go
- pkg/collector/helm2.go
- pkg/collector/helm2_test.go
- pkg/collector/helm3.go
- pkg/collector/helm3_test.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
The main reason for this PR is to fix Helm v3 collector name:
```diff
pkg/collector/helm3.go
- commonCollector: newCommonCollector("Helm v2"),
+ commonCollector: newCommonCollector("Helm v3"),
```
And I've also added a test to cover this, and that needed some small refactoring too :).
> Fix: Helm v3 collector name and refactoring to be test-friendly

- pkg/collector/helm.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/collector/helm_test.go
This PR should fix #124, after some tests the only way the OPA expressions will return nil namespace is if input has namespace nil / `null` in json. It seems it might be the case with Helm and interface assertions.
Used this opportunity to extract out some dupe code, and cover it with tests.
The `TestFixNamespace/nil` test was first added and failing before the fix.
> fix: Fix nil namespace helm

- cmd/kubent/main_test.go
- pkg/collector/cluster_test.go
- pkg/collector/file_test.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
- pkg/judge/rego_test.go
This PR mainly adds support for in-cluster authentication and some minor refactoring on tests.
This func. would deserve integration test, created #236.
> Add support for in-cluster auth

- pkg/rules/rego/deprecated-1-25.rego
This is a very simple fix that allows deprecated batch/v1beta1 CronJobs to be detected based on last-applied-configuration.
CronJob Kind was incorrectly specified as plural CronJobs.
Resolves #250
> fix: Fix CronJob rego

- fixtures/localsubjectaccessreview-v1beta1.yaml
- fixtures/selfsubjectaccessreview-v1beta1.yaml
- fixtures/subjectaccessreview-v1beta1.yaml
- fixtures/tokenreview-v1beta1.yaml
- pkg/rules/rego/deprecated-1-16.rego
- pkg/rules/rego/deprecated-1-22.rego
- pkg/rules/rego/deprecated-1-25.rego
- test/helper.go
This PR fixes non-working rules tests #252 and 2 other minor issues discovered once the tests started to work as expected:
- test: Fix review* fixture manifests to contain metadata
- fix: Resource name can be undefined in some cases
> Fix tests rules

- fixtures/volumesnapshot-v1beta1.yaml
- fixtures/volumesnapshotclass-v1beta1.yaml
- fixtures/volumesnapshotcontent-v1beta1.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-future.rego
- test/rules_future_test.go
This PR adds support for detecting now deprecated [^1] `snapshot.storage.k8s.io/v1beta1` resources:
- `VolumeSnapshot`
- `VolumeSnapshotClass`
- `VolumeSnapshotContent`
Fixes https://github.com/doitintl/kube-no-trouble/issues/87
Other minor changes introduced:
- [test: Reduce test noise level](https://github.com/doitintl/kube-no-trouble/commit/78e9edfd9e289d3c63714ea5cf3b5b6aa9c9d58f): reduce log level in tests to `WARN` to improve readability of tests output
[^1]: https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd
> feat: Add support for detecting snapshot.storage.k8s.io/v1beta1

- .github/workflows/main.yaml
- .pre-commit-config.yaml
- README.md
- cmd/kubent/main_test.go
- pkg/collector/file_test.go
- pkg/collector/kube_test.go
- pkg/printer/filter_test.go
- scripts/install.sh
- test/helper_test.go
- test/rules_122_test.go
- test/rules_125_test.go
- test/rules_future_test.go
This should fix spelling mistakes and future spelling mistakes. I have chosen to go with a pre-commit so it can be run locally ensuring that users can check for spelling mistakes on their own.
> chore: Fixing spelling and add pre-commit for it

- README.md
- cmd/kubent/main.go
- fixtures/fake-deployment-v1beta1-with-kapp-annotation.yaml
- pkg/collector/cluster.go
- pkg/collector/cluster_test.go
- pkg/config/config.go
Currently, kubent only checks the `kubectl.kubernetes.io/last-applied-configuration` annotation for deprecated APIs, which is set by kubectl. If a different tool like [kapp](https://github.com/vmware-tanzu/carvel-kapp) is used, which might set other annotations, kubent won't detect those.
This PR adds support for checking additional annotations. It can be activated via the `--additional-annotations` flag.
**Example:**
```shell
kubent -t v1.22 --additional-annotations kapp.k14s.io/original
```
The change is backward compatible, as the `kubectl.kubernetes.io/last-applied-configuration` annotation will always be checked first. Only if that annotation is not set the additional annotations are tried.
> feat: Support for checking additional annotations

- README.md
- cmd/kubent/main.go
- cmd/kubent/main_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/printer/json.go
- pkg/printer/json_test.go
- pkg/printer/printer.go
- pkg/printer/printer_test.go
- pkg/printer/text.go
- pkg/printer/text_test.go
This PR adds support for `-O` flag to configure output to a file to main binary and all the existing printers (json, text).
Related changes introduced:
- Increased test coverage for the common code and existing printers in the `printer` package
- Refactored Main tests to pass arguments via env variable, this was required to maintain consistency between runs (tmp dir)
Fixes #304
_Sonar CLoud complains about test func naming with underscores (which are generated by Goland and questionably a standard for unexported func tests in Go) and some repeated strings all in tests. I plan to ignore it... in the longer term, we should really get to enabling some linters in a way that makes sense), the SC is getting annoying._
> Add support for configuring output file

- fixtures/fake-ingress-v1beta1-with-annotation.yaml
- pkg/collector/cluster.go
Fixes #364
Use the v1 API to collect Ingress objects to avoid tripping metrics for use of deprecated APIs
> fix: Collect Ingress via v1 API

- pkg/collector/helm.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/collector/helm_test.go
This uses discovery client to check if given type of resource is namespaced. Discovery client should be cached, so it's fine to call ServerResourcesForGroupVersion() multiple times.
Fixes #195
> fix: Helm - only default to release namespace for namespaced resources

- .github/workflows/main.yaml
This PR should fix missing build info in Doker image binaries 🤞 
Fixes: #378
> ci: Fix missing build info in docker images

- .github/workflows/main.yaml
- Dockerfile
This should, hopefully 🤞, avoid rebuilding of the docker image with a different hash (and also currently broken as it's missing the build-args).
> ci: Fix latest tag and avoid rebuild

- pkg/collector/helm.go
- pkg/collector/helm_test.go
Helm's SplitManifests can keep empty documents (sometimes), this results in an unnecessary warning log line and unwanted empty resources.
before:
```bash
$./bin/kubent-darwin-amd64
1:14PM INF version dev (git sha dev)
1:14PM INF Initializing collectors and retrieving data
1:14PM INF Target K8s version is 1.22.12-gke.2300
1:14PM INF Retrieved 10 resources from collector name=Cluster
1:14PM INF Retrieved 0 resources from collector name="Helm v2"
1:14PM WRN failed to discover supported resources for : groupVersion shouldn't be empty
...
```
after:
```
$./bin/kubent-darwin-amd64                                                                                                                          0
1:15PM INF >>> Kube No Trouble `kubent` <<<
1:15PM INF version dev (git sha dev)
1:15PM INF …
```
> fix: Ignore empty documents from Helm collectors

- .github/workflows/main.yaml
- Makefile
- scripts/alpine-setup.sh
Another try to fix broken tags on docker building GH actions.
Currently nightly builds are broken, as the `${{ !startsWith(github.ref, 'refs/tags/nightly') && format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE_NAME, 'latest') }}` evaluates to `false`. After this change, it will evaluate to an empty string.
_Warning: not 100% sure this will work - while the syntax will return an empty string, I'm not 100% sure if the `docker/build-push-action@v3` action will deal with that. If this won't work, we can try the metadata action[^1], but that seems pretty complex too._
[^1]: https://github.com/docker/metadata-action
> ci: Fix latest tag issue in nightly builds

- .github/workflows/main.yaml
This PR upgrade the `kind` CI action to latest, and versions of K8S used integration tests to 1.19 .. 1.25 (this is the set supported in latest kind release [^1]).
[^1]: https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0
> ci: Upgrade integration test versions to 1.19-1.25

- cmd/kubent/main.go
- cmd/kubent/main_test.go
- go.mod
- go.sum
- pkg/collector/kube.go
- pkg/collector/kube_test.go
This PR disables warnings from K8S go-client. Unfortunately, this is not sufficient to also suppress the warning about deprecated auth plugins, therefore the need for klog output code too.
But in general any direct logging from 3rd-party libs is undesirable, and this configures K8S's go-client klog to discard any logs.
I've added some tests to cover some unexpected 3rd-party output, but asthis depends on the environment and kubeconfig config, incl. providers, and is not easily reproducible, this should be covered by an integration test, as the current test does not fully cover this. Opened #406.
fixes #402
Compare output from #402 (pre) with the following (post) - the warnings from klog are gone:
```shell
$ ./bin/kubent-darwin-amd64
11:35AM INF >>> Kube No Trouble `kubent` <<<
11:35AM INF …
```
> feat: Disable any logging from go-client's klog

- .github/workflows/stale.yaml
After the initial "stale" workflow run and storm of issues marked as stale, and going through these, I suggest some minor tuning of this workflow config
- Recognize `not-stale` label
- Unify times for issues and PRs to 60 + 30 - 90 days in total before closing
- Updated somewhat weird default messages.
> ci: Tune stale issues/PRs workflow config to wait a bit longer (60+30)

- .codespellrc
Codespell wrongly flags `go.sum` [^1]. This PR should make it ignore the file.
[^1]: https://github.com/doitintl/kube-no-trouble/actions/runs/4233400288/jobs/7354317644
> chore: Codespell should ignore go.sum

- .github/workflows/main.yaml
- Dockerfile
Adding support for building arm64 docker image in the same manifest.
Also removing docker build step as results are not used and with release image rebuild anyway. I'd argue that the fact that it builds outside of docker means it will build inside of it and there is no reason to break the build, but I can go either way.
[Here is a build on my repo](https://github.com/kkopachev/kube-no-trouble/actions/runs/4208948274/jobs/7305507674#step:4:253)
> feat: Build Docker Arm64 images

- pkg/rules/rego/deprecated-1-25.rego
- pkg/rules/rego/deprecated-1-26.rego
- test/rules_125_test.go
- test/rules_126_test.go
> fix: Move autoscaling/v2beta1 removed to Kubernetes 1.25

- README.md
Added brew installation method to README with reference to https://formulae.brew.sh/formula/kubent
> chore: Add brew installation method

- fixtures/csistoragecapacity-v1beta1.yaml
- fixtures/flowschema-v1beta1.yaml
- fixtures/flowschema-v1beta2.yaml
- fixtures/prioritylevelconfiguration-v1beta1.yaml
- fixtures/prioritylevelconfiguration-v1beta2.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-27.rego
- pkg/rules/rego/deprecated-1-29.rego
- test/rules_126_test.go
- test/rules_127_test.go
- test/rules_129_test.go
This PR is adding the following deprecations.
- [v1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26) `flowcontrol` 
- [v1.27](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27) `CSIStorageCapacity`
- [v1.29](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-29) `flowcontrol`
This has been tested with the resources included inside fixtures in a k8s v1.24 running cluster. Here is the output:
```
❯ ./bin/kubent -t 1.26
1:08PM INF >>> Kube No Trouble `kubent` <<<
1:08PM INF version dev (git sha dev)
1:08PM INF Initializing collectors and retrieving data
1:08PM INF Target K8s version is 1.26.0
1:08PM INF Retrieved 198 resources from collector name=Cluster
1:08PM INF Retrieved 7 resources from collector name="Helm v3"
1:08PM …
```
> feat: add 1.26 1.27 1.29 deprecations

- cmd/kubent/main.go
- cmd/kubent/main_test.go
Error, errors out properly closes #450 and increased log level for silent resource failures
> fix: Return error exit code when collectors fail

- scripts/install.sh
When $TERM is dumb the number of colours returned is -1 we end up with no values set for the colours.
To test this:
```bash
export TERM=dumb
sh -c "$(curl -sSL https://git.io/install-kubent)"
```
You should get an error regarding parameter expansion:
```
sh: 96: GREEN: parameter not set
```
This PR fixes the issue by initialising the variables no matter what.
> fix: install.sh in dumb TERM

- pkg/judge/rego.go
This is to avoid issues such as https://github.com/doitintl/kube-no-trouble/issues/505. I have been seeing this error myself, which manifests as:
```
10:53AM TRC parsing +map[ApiVersion:batch/v1beta1 Kind:CronJob Name:resource123 Namespace:<nil> ReplaceWith:batch/v1 RuleSet:Deprecated APIs removed in 1.25 Since:1.21]
panic: interface conversion: interface {} is nil, not string
```
This is a simple PR which just warns the user that the object's namespace was not collected correctly and then sets it to `<undefined>`. The message could also be amended to ask the user to report the issue to the developer. I figure this is a better outcome then a panic, and it also fixes the problem I (and presumably others) was having.
> Warn and Fix Up Invalid Namespaces on Objects

- .pre-commit-config.yaml
- cliff.toml
A maintainer decide merge master into several prs. Creating a history nightmare. So now we need to clean and go through all the changes made.
> chore(clean): Clean up mess from double merge master into prs

- .github/CONTRIBUTING.md
- README.md
Applogies for the other pr, it eventually got out of hand. So I am introducing a contribution document. See the referenced message again. Once again appologies for the spam.
> Seeing how there has been some confusion over how to operate this repo, I have added more details for the maintianers to discuss.
> @migueldelucasdoit Please read and approve if you agree.
> It is desirable that these rules are followed. Not just for the sake of following them but for the purpose of maintaining standards.
> fix(contributions): Add Contributing file

- .github/CONTRIBUTING.md
This documents what is expected of contributors and maintainers when it comes to releases and tagging. As well as how the nightly release process works. Please review and agree if you are a maintainer.
> docs(release): Document the release process and what is expected
