- scripts/install.sh
This PR adds install script for convenience.
> Add install script

- .gitignore
- fixtures/ca.crt
- fixtures/kube.config
- pkg/collector/cluster_test.go
- pkg/collector/collector_test.go
- pkg/config/config_test.go
> More tests with some fixtures

- cmd/kubent/main.go
https://github.com/doitintl/kube-no-trouble/issues/25
> Fixing panic when collector name is nil

- pkg/collector/cluster.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
- pkg/judge/rego.go
This fixes missing resources from collectors #30 
This should really be covered by tests. Apart from integration tests (I think that's the way to go), it seems like Kubernetes offer fairly useable fake client which might be helpful here - https://gianarb.it/blog/unit-testing-kubernetes-client-in-go.
> Fix missing resources

- pkg/collector/file.go
- pkg/collector/file_test.go
This fixes incorrectly collected resources with file collector - #38, and improves tests to cover such issue.
> Fix file collector

- CHANGELOG.md
- Makefile
Small fix for #39 and add release notes for 0.3.2
> Sha fix and release notes for 0.3.2

- pkg/collector/file.go
This should fix recently added flaky test #42, which relies on the order of manifests.
> test: Make manifest order read by file collector stable

- .github/workflows/main.yaml
- Dockerfile
- go.mod
> Updated Golang to 15

- Makefile
🤞 this will finally allow the nightly builds to work
> build: Allow hyphens in tags - for nightly

- README.md
- cmd/kubent/main.go
- cmd/kubent/main_test.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/config_test.go
> feat: Configurable log level

- cmd/kubent/main.go
- cmd/kubent/main_test.go
- pkg/config/config.go
- pkg/config/zerologlevel.go
- pkg/printer/json.go
- pkg/printer/json_test.go
- pkg/printer/printer.go
- pkg/printer/printer_test.go
- pkg/printer/text.go
> ref: Printer Updates

- Makefile
> chore: Make UPX go faster

- .github/workflows/main.yaml
ARM for arm linux + mac machines, closes #144
> feat: Build arm for linux and darwin

- .github/workflows/main.yaml
> ci: Integration test

- .github/workflows/main.yaml
> fix: Fix for wrong file path for downloaded archive in integration test

- pkg/collector/cluster.go
- pkg/collector/file.go
- pkg/collector/file_test.go
- pkg/collector/helm2.go
- pkg/collector/helm3.go
> ref: Continue if individual manifest fails

- pkg/judge/rego.go
This PR adds additional TRACE-level logging to debug #124
> chore: Add additional trace output in rego Eval() fn

- .github/workflows/main.yaml
- .github/workflows/nightly.yaml
> ci: Update GH checkout action to v2

- README.md
- cmd/kubent/main.go
- cmd/kubent/main_test.go
- pkg/config/config.go
> feat: Version flag

- .github/workflows/main.yaml
- .github/workflows/nightly.yaml
- Dockerfile
- go.mod
- go.sum
- scripts/git-check-commits.sh
- scripts/github-changelog.sh
Part of https://github.com/doitintl/kube-no-trouble/issues/306
> ci: update checkout action to lastest

- README.md
Update link to blog post (fixes #272)
> docs: Update link to blog

- .github/workflows/main.yaml
- Dockerfile
- go.mod
- go.sum
- scripts/alpine-setup.sh
- scripts/git-check-commits.sh
- scripts/github-changelog.sh
> feat(golang19): update to golang 19, go mod tidy too

- README.md
This PR adds an example of how to run kubent on bunch of files in a directory using shell.
Fixes #211
> docs: Add example of scanning all files in a directory

- cmd/kubent/main.go
- pkg/collector/cluster.go
- pkg/collector/cluster_test.go
- pkg/collector/helm2.go
- pkg/collector/helm2_test.go
- pkg/collector/helm3.go
- pkg/collector/helm3_test.go
- pkg/collector/kube.go
- pkg/collector/kube_test.go
> feat: Display correct version in User-Agent HTTP header

- cmd/kubent/main_test.go
- fixtures/expected-json-output.json
Ensuring json returns empty array and text stdout is empty when no issues are found
> chore: Test empty output

- scripts/install.sh
> chore: Users can install latest nightly

- scripts/install.sh
> ci: Notify users of the aarch64 option when installing

- fixtures/autoscaler-v2beta1.yaml
- fixtures/autoscaler-v2beta2.yaml
- pkg/collector/cluster.go
- pkg/rules/rego/deprecated-1-26.rego
- test/rules_125_test.go
- test/rules_126_test.go
Closes https://github.com/doitintl/kube-no-trouble/pull/330
> feat: Cover deprecated autoscaling/v2beta1 and autoscaling/v2beta2

- .github/workflows/main.yaml
- scripts/changelog.tmpl
> fix: Full path of the docker registry

- pkg/collector/helm.go
> chore: Add debug-level logging to Helm collectors

- .github/workflows/stale.yaml
> ci: Auto-close stale issues/PRs

- .github/workflows/stale.yaml
> ci: Remove duplicated lines from GH stale workflow

- .github/workflows/main.yaml
- Dockerfile
- go.mod
> feat: Golang 1.20

- .github/workflows/main.yaml
- .pre-commit-config.yaml
Try to fix https://github.com/doitintl/kube-no-trouble/actions/runs/6706401680/job/18223278567#step:4:103
> ci: Upgrade pre-commit action to v3

- pkg/config/config.go
Default to kubeconfig when blank, mirrors kubectl behavoir
> feat(default): Default to kubeconfig when kubeconfig is empty string

- .github/workflows/main.yaml
- .gitignore
> fix(gitcliff): Add fix for git cliff

- .github/dependabot.yml
- .github/workflows/main.yaml
• Upgrade actions/upload-artifact from v1 to v4
• Upgrade actions/download-artifact from v1 to v4
• Add migueldelucasdoit as dependabot reviewer
> Fix workflows

- .github/copilot/copilot.yml
> chore(copilot): Begone
